#!/bin/bash
set -euo pipefail

SERVICE_NAME="tri-core-autogen.service"
USER_SYSTEMD_DIR="$HOME/.config/systemd/user"
SERVICE_FILE="$USER_SYSTEMD_DIR/$SERVICE_NAME"

mkdir -p "$USER_SYSTEMD_DIR"

cat > "$SERVICE_FILE" <<'SERVICE'
[Unit]
Description=Tri Core Autogenerated Service

[Service]
ExecStart=/usr/bin/env bash -c 'echo service running'
Restart=on-failure

[Install]
WantedBy=default.target
SERVICE

systemctl --user daemon-reload
systemctl --user enable --now "$SERVICE_NAME"

echo "Service $SERVICE_NAME installed and started."
